### ISSUE TITLE
HID Plugin

### ISSUE THREAD

**Issue by divinemayhem** [boredland/spreadpi-upgrade#4]
The script runs almost perfectly! The only issue that I've been able to find is that the HIDTrigger plugin cannot be selected. The following error appears when you attempt to select it in the $ spread configure dialog: 

spreads encountered an error:
Traceback (most recent call last):
  File "/home/bookscanner/Downloads/leptonica-1.71/scantailor-enhanced/spreads-0.5git20150226.924b/spreads/main.py", line 321, in main
    run()
  File "/home/bookscanner/Downloads/leptonica-1.71/scantailor-enhanced/spreads-0.5git20150226.924b/spreads/main.py", line 308, in run
    args.subcommand(config)
  File "/home/bookscanner/Downloads/leptonica-1.71/scantailor-enhanced/spreads-0.5git20150226.924b/spreads/cli.py", line 210, in configure
    _setup_processing_pipeline(config)
  File "/home/bookscanner/Downloads/leptonica-1.71/scantailor-enhanced/spreads-0.5git20150226.924b/spreads/cli.py", line 141, in _setup_processing_pipeline
    exts = [name for name, cls in plugin.get_plugins(*config["plugins"].get())
  File "/home/bookscanner/Downloads/leptonica-1.71/scantailor-enhanced/spreads-0.5git20150226.924b/spreads/plugin.py", line 421, in get_plugins
    .format(name, message, name))
ExtensionException: Missing Python dependency for extension 'hidtrigger': hidapi

**Comment by divinemayhem** [comment]
I've grabbed the hidapi files from GitHub (https://github.com/signal11/hidapi.git), but I'm unsure of what to do next. The readme states that "The Linux version of HIDAPI is designed to be dropped directly into your application. This is in contrast to the Windows version, which must
currently be built into a DLL."

I read that as "The files should be placed somewhere in the application's directory." Where?

**Comment by boredland** [comment]
Nevermind, added an installer for hidapi, jbaiter did put that one into his
installer.

Just do a "git pull" to get the newest version of this script from git and
re-run.

2015-02-27 17:20 GMT+01:00 divinemayhem notifications@github.com:

**Comment by boredland** [comment]
Explicitly: pip install -e ".[hidtrigger]" in Line 164 was added.
